import React,{useState} from 'react';
import './Sign-in.css';import {Link} from "react-router-dom";
import axios from 'axios';


export default function SignIn() {

    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');
    const [confirmPassword, setConfirmPassword] = useState('');
    const [email, setEmail] = useState('');

    const userRegister = (event) => {
        event.preventDefault();

        if (!username) {
            alert('Username is required.');
            return;
        }

        if (!/^[A-Za-z ]+$/.test(username)) {
            alert('Please give a correct username.');
            return;
        }

        if (!password) {
            alert('Password is required.');
            return;
        }

        if (password.length < 5) {
            alert('Password must be at least 5 characters long.');
            return;
        }

        if (!/^(?=.*[A-Za-z])(?=.*\d).{5,}$/.test(password)) {
            alert('Password must have at least one alphabetic character (uppercase or lowercase), at least one digit (0-9), and a minimum length of 5 characters.');
            return;
        }

        if (!/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test(email)) {
            alert('Please enter a correct email address.');
            return;
        }

        if (password !== confirmPassword) {
            alert('Password and confirm password do not match.');
            return;
        }

        const user = {
            username,
            password,
            email,
        };


        axios.post(`${process.env.REACT_APP_API_URL}/user`, user)
            .then(response => {

                alert(`Please log in to continue, and kindly remember this one-time autogenerated ID for future interactions. Your user ID is: ${response.data}`);
                setUsername('');
                setPassword('');
                setConfirmPassword('');
                setEmail('');
            })
            .catch(error => {
                console.error(error);
            });
    };

    return (
        <div className='container-fluid'>
            <div className='row'>

                <header className='d-flex justify-content-between align-items-center p-1'>
                    <h1 className='text-white'>User Registration</h1>
                    <button id="btnLogIn" ><Link  className='text-black text-decoration-none' to="/">Log in</Link></button>
                </header>
                <div className="col-md-10">
                    <div className="container">

                        <form onSubmit={userRegister}>
                            <label htmlFor="username">Username:</label>
                            <input
                                type="text"
                                id="username"
                                value={username}
                                onChange={(e) => setUsername(e.target.value)}
                                required
                                pattern="[A-Za-z ]+"
                            />
                            <br />

                            <label htmlFor="password">Password:</label>
                            <input
                                type="password"
                                id="password"
                                value={password}
                                onChange={(e) => setPassword(e.target.value)}
                                required
                                pattern="(?=.*[A-Za-z])(?=.*\d).{5,}"
                            />
                            <br />

                            <label htmlFor="confirmPassword">Confirm Password:</label>
                            <input
                                type="password"
                                id="confirmPassword"
                                value={confirmPassword}
                                onChange={(e) => setConfirmPassword(e.target.value)}
                                required
                            />
                            <br />

                            <label htmlFor="email">Email:</label>
                            <input
                                type="email"
                                id="email"
                                value={email}
                                onChange={(e) => setEmail(e.target.value)}
                                required
                            />
                            <br />

                            <button type="submit">Register</button>
                        </form>


                    </div>
                </div>

            </div>

        </div>
    );
}


