import React,{useState} from 'react';
import './Loan-account.css'
import Navigation from "../../components/Navigation/Navigation";
import {Link} from "react-router-dom";
import axios from "axios";
import Big from "big.js";

export default function LoanAccount() {

    // Loan Account Creation Form State
    const [loanAmount, setLoanAmount] = useState('');
    const [createDate, setCreateDate] = useState('');
    const [interestRate, setInterestRate] = useState('');
    const [accountId, setAccountId] = useState('');
    const [accountNumber, setAccountNumber] = useState('');
    const [amount, setAmount] = useState('');

    const onLoanAccountFormSubmit = async (event) => {
        event.preventDefault();

        const loanAccount = {
            loanAmount: loanAmount,
            createDate: createDate,
            interestRate: interestRate,
            accountId: accountId,
        };

        try {
            const response = await axios.post(`${process.env.REACT_APP_API_URL}/loanaccount`, loanAccount);
            alert(`Successfully created, and kindly remember this one-time autogenerated Loan Account ID for future interactions. Your Loan account id is: ${response.data}`);
        } catch (error) {
            console.error(error);
        }
    };


    const onUpdateLoan = async (event) => {
        event.preventDefault();
        try {
            await axios.patch(`${process.env.REACT_APP_API_URL}/loanaccount/loanrepay/${accountNumber}`, new Big(amount));
            alert('Successfully updated');
        } catch (error) {
        console.error('Error:', error);

        if (error.response) {
            console.error('Response:', error.response.data);
        }
    }

};


    return (
        <div className='container-fluid'>
            <div className='row'>
                <header className='d-flex justify-content-between align-items-center p-1'>
                    <h1 className='text-white'>Loan account</h1>
                    <button id='logOutBtn' className='btn btn-danger'><Link className='text-black text-decoration-none' to="/">Log out</Link></button>
                </header>
                <Navigation/>
                <div className="col-md-10">
                    <div id="containerWrap" className="d-flex justify-content-center">
                        {/* Loan Account Creation Form */}
                        <div className="container">
                            <h2>Loan Account Creation</h2>
                            <form onSubmit={onLoanAccountFormSubmit}>
                                <label htmlFor="loanAmount">Loan Amount:</label>
                                <input
                                    type="number"
                                    id="loanAmount"
                                    name="loanAmount"
                                    value={loanAmount}
                                    onChange={(e) => setLoanAmount(e.target.value)}
                                    required
                                    step="0.01"
                                />
                                <br />

                                <label htmlFor="createDate">Create Date:</label>
                                <input
                                    type="date"
                                    id="createDate"
                                    name="createDate"
                                    value={createDate}
                                    onChange={(e) => setCreateDate(e.target.value)}
                                    required
                                />
                                <br />

                                <label htmlFor="interestRate">Interest Rate:</label>
                                <input
                                    type="number"
                                    id="interestRate"
                                    name="interestRate"
                                    value={interestRate}
                                    onChange={(e) => setInterestRate(e.target.value)}
                                    required
                                    step="0.01"
                                />
                                <br />

                                <label htmlFor="accountId">Account Id:</label>
                                <input
                                    type="number"
                                    id="accountId"
                                    name="accountId"
                                    value={accountId}
                                    onChange={(e) => setAccountId(e.target.value)}
                                    required
                                />
                                <br />

                                <button type="submit">Create</button>
                            </form>
                        </div>

                        {/* Loan Repayment Form */}
                        <div className="container2">
                            <h2>Loan Repayment</h2>
                            <form onSubmit={onUpdateLoan}>
                                <label htmlFor="accountNumber">Account Number:</label>
                                <input
                                    type="text"
                                    id="accountNumber"
                                    name="accountNumber"
                                    value={accountNumber}
                                    onChange={(e) => setAccountNumber(e.target.value)}
                                    required
                                />
                                <br />

                                <label htmlFor="amount">Amount:</label>
                                <input
                                    type="number"
                                    id="amount"
                                    name="amount"
                                    value={amount}
                                    onChange={(e) => setAmount(e.target.value)}
                                    required
                                    step="0.01"
                                />
                                <br />

                                <button type="submit">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    );
}


