import React,{useState} from 'react';
import './Savings-account.css'
import Navigation from "../../components/Navigation/Navigation";
import {Link} from "react-router-dom";
import axios from "axios";

export default function SavingsAccount() {

    const [interestRate, setInterestRate] = useState('');
    const [withdrawalLimit, setWithdrawalLimit] = useState('');
    const [accountId, setAccountId] = useState('');


    const savingAccountCreation = (event) => {
        event.preventDefault();

        const javascriptDate = new Date();
        const year = javascriptDate.getFullYear();
        const month = String(javascriptDate.getMonth() + 1).padStart(2, '0');
        const day = String(javascriptDate.getDate()).padStart(2, '0');
        const formattedDate = `${year}-${month}-${day}`;

        const savingsAccount = {
            createDate: formattedDate,
            interestRate,
            withdrawalLimit,
            accountId,
        };

        axios.post(`${process.env.REACT_APP_API_URL}/savingaccount`, savingsAccount)
            .then((response) => {
                alert(`Successfully created, and kindly remember this one-time autogenerated Savings Account ID for future interactions. Your Savings account id is: ${response.data}`);

                setInterestRate('');
                setWithdrawalLimit('');
                setAccountId('');

            })
            .catch((error) => {
                console.log(error);
            });


    };

    return (
        <div className='container-fluid'>
            <div className='row'>
                <header className='d-flex justify-content-between align-items-center p-1'>
                    <h1 className='text-white'>Savings account</h1>
                    <button id='logOutBtn' className='btn btn-danger'><Link className='text-black text-decoration-none' to="/">Log out</Link></button>
                </header>
                <Navigation/>

                <div className="col-md-10">

                    <div className="container">
                        <h2>Savings Account Creation </h2>
                        <form onSubmit={savingAccountCreation}>
                            <label htmlFor="interestRate">Interest Rate:</label>
                            <input
                                type="number"
                                id="interestRate"
                                value={interestRate}
                                onChange={(e) => setInterestRate(e.target.value)}
                                required
                                step="0.01"  // Adjust the step attribute based on your requirements
                            />
                            <br />

                            <label htmlFor="withdrawalLimit">Withdrawal Limit:</label>
                            <input
                                type="number"
                                id="withdrawalLimit"
                                value={withdrawalLimit}
                                onChange={(e) => setWithdrawalLimit(e.target.value)}
                                required
                                step="0.01"  // Adjust the step attribute based on your requirements
                            />
                            <br />

                            <label htmlFor="accountId">Account Id:</label>
                            <input
                                type="number"
                                id="accountId"
                                value={accountId}
                                onChange={(e) => setAccountId(e.target.value)}
                                required
                            />
                            <br />

                            <button type="submit">Create</button>
                        </form>
                    </div>
                </div>

            </div>

        </div>
    );
}


