import React, {useState} from 'react';
import './Account.css';
import Navigation from "../../components/Navigation/Navigation";
import {Link} from "react-router-dom";
import Big from 'big.js';
import axios from "axios";

export default function Account() {

    const [accountType, setAccountType] = useState('');
    const [initialDeposit, setInitialDeposit] = useState('');
    const [userId, setUserId] = useState('');
    const [accountNumber, setAccountNumber] = useState('');
    const [balance, setBalance] = useState('');

    const createAccount = (event) => {
        event.preventDefault();

        const account = {
            accountType: accountType,
            balance: new Big(+initialDeposit),
            userId: +userId,
        };
        axios.post(`${process.env.REACT_APP_API_URL}/account`, account)
            .then(response => {

                alert(`Successfully created, and kindly remember this one-time autogenerated Account ID for future interactions. Your account id is: ${response.data}`);
                setAccountType('');
                setInitialDeposit('');
                setUserId('');

            })
            .catch(error => {
                console.error(error);
            });

    };

    const checkBalance = (event) => {
        event.preventDefault();

        axios.get(`${process.env.REACT_APP_API_URL}/account/${accountNumber}`)
            .then(response => {

                if (response.data === null) {
                    alert('Please insert a correct account number');
                } else {
                    setBalance(response.data);
                }

            }).catch(error => {
            console.log(error);
        });


    };

    return (
        <div className='container-fluid'>
            <div className='row'>
                <header className='d-flex justify-content-between align-items-center p-1'>
                    <h1 className='text-white'>All accounts</h1>
                    <button id='logOutBtn' className='btn btn-danger'><Link className='text-black text-decoration-none'
                                                                            to="/">Log out</Link></button>
                </header>
                <Navigation/>
                <div className="col-md-10">
                    <div id="containerWrap" className="d-flex justify-content-center">
                        <div className="container mx-auto">
                            <h2>Account Creation</h2>
                            <form onSubmit={createAccount}>
                                <label htmlFor="accountType">Account Type:</label>
                                <select
                                    id="accountType"
                                    value={accountType}
                                    onChange={(e) => setAccountType(e.target.value)}
                                    required
                                >
                                    <option value="LoanAccount">Loan</option>
                                    <option value="FixedDepositAccount">Fix Deposit</option>
                                    <option value="SavingsAccount">Saving</option>
                                </select>

                                <label htmlFor="initialDeposit">Initial Deposit:</label>
                                <input
                                    type="number"
                                    id="initialDeposit"
                                    value={initialDeposit}
                                    onChange={(e) => setInitialDeposit(e.target.value)}
                                    required
                                    step="0.01"
                                />

                                <label htmlFor="userId">User ID:</label>
                                <input
                                    type="number"
                                    id="userId"
                                    value={userId}
                                    onChange={(e) => setUserId(e.target.value)}
                                    required
                                />
                                <br/>
                                <button type="submit">Create</button>
                            </form>
                        </div>


                        <div className="container2 mx-auto">
                            <h2>Balance Inquiry</h2>
                            <form onSubmit={checkBalance}>
                                <label htmlFor="accountNumber">Account Number:</label>
                                <div id='wrap'>
                                    <input
                                        type="text"
                                        id="accountNumber"
                                        value={accountNumber}
                                        onChange={(e) => setAccountNumber(e.target.value)}
                                    />
                                    <button type="submit">Search</button>
                                </div>
                                <label htmlFor="balance">Balance:</label>
                                <input
                                    type="text"
                                    id="balance"
                                    value={balance}
                                    disabled
                                    className='bg-white'
                                />
                            </form>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    );
}


